<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>EmbyMemoryCleaner</AssemblyName>
    <RootNamespace>EmbyMemoryCleaner</RootNamespace>
    <Version>1.0.3.2</Version>
    <FileVersion>1.0.3.2</FileVersion>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <!-- 杩欎笁涓?DLL 闇€瑕佷粠浣犺嚜宸辩殑 Emby Server 瀹夎鐩綍澶嶅埗鍒?refs/ 鏂囦欢澶逛笅锛?
         Windows: C:\Users\<浣?\AppData\Roaming\Emby-Server\system\
         Docker:  /system/  閲岀殑鍚屽悕鏂囦欢
         Linux:   /opt/emby-server/system/
    -->
    <Reference Include="MediaBrowser.Common">
      <HintPath>refs\MediaBrowser.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MediaBrowser.Controller">
      <HintPath>refs\MediaBrowser.Controller.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MediaBrowser.Model">
      <HintPath>refs\MediaBrowser.Model.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Configuration\configPage.html" />
    <EmbeddedResource Include="Configuration\configPage.js" />
    <EmbeddedResource Include="Images\thumb.png" />
  </ItemGroup>

</Project>
